name: WebUI E2E Tests

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      name:
        required: true
        type: string

jobs:
  e2e:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:dind
        options: --privileged --shm-size=2g
    strategy:
      matrix:
        browser: [ firefox ]
        # browser: [ firefox, chromium, webkit ]
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
        with:
          path: src

      - name: Define PREFIX
        run: echo "PREFIX=${GITHUB_WORKSPACE}/install" >> "$GITHUB_ENV"

      - name: Download rspamd binary from build job
        uses: actions/download-artifact@v4
        with:
          name: rspamd-binary-ubuntu-ci
          path: ${{ env.PREFIX }}

      - name: Prepare rspamd configuration
        run: |
          mkdir -p ${PREFIX}/etc/rspamd/local.d
          cp -a src/conf/. "${PREFIX}/etc/rspamd/"
          echo 'static_dir = "/__w/rspamd/rspamd/install/share/rspamd/www";' > ${PREFIX}/etc/rspamd/local.d/worker-controller.inc
          echo "bind_socket = \"*:11334\";" >> ${PREFIX}/etc/rspamd/local.d/worker-controller.inc
          cat > ${PREFIX}/etc/rspamd/local.d/logging.inc << 'EOF'
          type = "console";
          level = "info";
          EOF
          # Disable multimap module to prevent hyperscan cache issues at runtime
          echo 'enabled = false;' > ${PREFIX}/etc/rspamd/local.d/multimap.conf
          # Disable redis dependent modules for WebUI tests
          echo 'redis { enabled = false; }' > ${PREFIX}/etc/rspamd/local.d/modules.conf
          chmod +x ${PREFIX}/bin/rspamd

      - name: Prepare host runtime dirs
        run: |
          sudo mkdir -p /var/run/rspamd /var/lib/rspamd
          sudo chown $USER:$USER /var/run/rspamd /var/lib/rspamd

      - name: Create network and start rspamd container
        shell: bash -e {0}
        run: |
          docker network create rspamd-test-network || true
          docker run -d \
            --name rspamd-container \
            --network rspamd-test-network \
            -p 11334:11334 \
            -v "${PREFIX}":/__w/rspamd/rspamd/install \
            -v /var/run/rspamd:/var/run/rspamd \
            -v /var/lib/rspamd:/var/lib/rspamd \
            -e LD_LIBRARY_PATH=/__w/rspamd/rspamd/install/lib/rspamd \
            -e RSPAMD_LUA_PATH=/__w/rspamd/rspamd/install/share/rspamd/lualib \
            -e LUA_PATH="/__w/rspamd/rspamd/install/share/rspamd/lualib/?.lua;/__w/rspamd/rspamd/install/share/rspamd/lualib/?/init.lua;;" \
            -e LUA_CPATH="/__w/rspamd/rspamd/install/lib/rspamd/?.so;;" \
            -e GCOV_PREFIX=/tmp/gcov \
            -e GCOV_PREFIX_STRIP=5 \
            ghcr.io/rspamd/rspamd-build-docker:ubuntu-ci \
            /__w/rspamd/rspamd/install/bin/rspamd \
              -c /__w/rspamd/rspamd/install/etc/rspamd/rspamd.conf \
              --insecure

          # Wait for Docker daemon to be ready
          timeout 30s sh -c 'until docker info; do sleep 1; done'

          # Wait up to 240 seconds for WebUI to respond
          max_retries=120
          for i in $(seq 1 "$max_retries"); do
            # Try HTTP request with detailed output
            http_code=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:11334/ping || true)

            if [[ "$http_code" == "200" ]]; then
              echo "Rspamd WebUI is up (HTTP 200) after $((i * 2)) seconds"
              echo "Checking if rspamd is listening on port 11334..."
              docker exec rspamd-container netstat -tlnp | grep ":11334" && echo "Port 11334 is listening"
              break
            elif [[ "$http_code" != "000" ]]; then
              echo "Unexpected HTTP code $http_code from /ping; failing"
              exit 1
            fi

            echo "Waiting for rspamd... ($i/$max_retries) - HTTP code: $http_code"
            sleep 2
          done

          if [[ "$i" -eq "$max_retries" && "$http_code" != "200" ]]; then
            total_wait=$(( max_retries * 2 ))
            echo "ERROR: rspamd WebUI did not become available after $total_wait seconds"
            docker exec rspamd-container netstat -tlnp | grep ":11334" || echo "Port 11334 not found"
            docker exec rspamd-container ps aux | grep rspamd || echo "No rspamd process found"
            exit 1
          fi

      - name: Debug rspamd container logs if it fails to start
        if: always()
        run: |
          echo "::group::Last 100 lines of container logs"
          docker logs rspamd-container --tail 100 || true
          echo "::endgroup::"
          echo "::group::Full container logs"
          docker logs rspamd-container || true
          echo "::endgroup::"
          echo "Process list:"
          docker exec rspamd-container ps aux || true
          echo "Filesystem contents of PREFIX:"
          docker exec rspamd-container ls -lR /__w/rspamd/rspamd/install || true
          echo "Shared library check:"
          docker exec rspamd-container ldd /__w/rspamd/rspamd/install/bin/rspamd || true

      - name: Verify WebUI static assets
        run: |
          for asset in index.html css/rspamd.css js/main.js img/rspamd_logo_navbar.png; do
            curl -fsSo /dev/null http://localhost:11334/$asset || (echo "Missing $asset" && exit 1)
          done

      - name: Run TestCafe tests in separate container
        shell: bash -e {0}
        run: |
          docker run --rm \
            --network rspamd-test-network \
            -v ${{ github.workspace }}/src/test/webui-e2e:/tests \
            -w /tests \
            testcafe/testcafe:latest \
            firefox:headless tests/*.js --reporter spec
