name: WebUI E2E Tests

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      name:
        required: true
        type: string

jobs:
  e2e:
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.image }}
      options: --user root
    strategy:
      matrix:
        browser: [firefox]
        # browser: [firefox, chromium]
    steps:
      - name: Create directories
        run: |
          sudo mkdir -p ${GITHUB_WORKSPACE}

      - name: Check out source code
        uses: actions/checkout@v4
        with:
          path: src

      - name: Set variables on ARM64
        if: runner.arch == 'ARM64'
        run: echo "HYPERSCAN_ALTROOT=-DHYPERSCAN_ROOT_DIR=/vectorscan" >> "$GITHUB_ENV"

      - name: Run cmake
        run: |
          mkdir ${GITHUB_WORKSPACE}/build
          cd ${GITHUB_WORKSPACE}/build
          if [[ -f /opt/rh/gcc-toolset-10/enable ]] ; then source /opt/rh/gcc-toolset-10/enable ; fi
          cmake -DCMAKE_INSTALL_PREFIX=${GITHUB_WORKSPACE}/install -DCMAKE_RULE_MESSAGES=OFF -DCMAKE_VERBOSE_MAKEFILE=ON -DENABLE_COVERAGE=ON -DENABLE_LIBUNWIND=ON -DENABLE_LUAJIT=ON -DLUA_ROOT=/luajit-build -DENABLE_HYPERSCAN=ON ${{ env.HYPERSCAN_ALTROOT }} ${GITHUB_WORKSPACE}/src

      - name: Build rspamd
        run: |
          if [[ -f /opt/rh/gcc-toolset-10/enable ]] ; then source /opt/rh/gcc-toolset-10/enable ; fi
          cd ${GITHUB_WORKSPACE}/build
          ncpu=$(getconf _NPROCESSORS_ONLN)
          make -j $ncpu install
          make -j $ncpu rspamd-test
          make -j $ncpu rspamd-test-cxx

      - name: Prepare config
        run: |
          mkdir -p test-cfg/local.d
          cp -r src/conf/* test-cfg/
          echo 'static_dir = "../../interface";' > test-cfg/local.d/worker-controller.inc
          echo "log_file = "";\ntype = \"console\";\nlevel = \"info\";\n" > test-cfg/local.d/logging.inc
          ls -la test-cfg
          cat test-cfg/local.d/logging.inc
      - name: Install curl
        run: yum install -y curl || apt-get update && apt-get install -y curl
      - name: Start rspamd
        run: |
          ${GITHUB_WORKSPACE}/build/src/rspamd -c test-cfg/rspamd.conf --no-fork --insecure &
          for i in {1..10}; do curl -sf http://localhost:11334/ && exit 0 || sleep 2; done
          echo "ERROR: rspamd WebUI did not become available on http://localhost:11334/"
          exit 1
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Playwright
        run: npm install -g playwright
      - name: Install browsers
        run: npx playwright install --with-deps ${{ matrix.browser }}
      - name: Run WebUI E2E tests
        run: npx playwright test --project=${{ matrix.browser }}
        working-directory: src/test/webui-e2e
