name: WebUI E2E Tests

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      name:
        required: true
        type: string

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    container:
      image: ${{ inputs.image }}
      options: --user root
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
        with:
          path: src

      - name: Define install prefix
        run: echo "PREFIX=${GITHUB_WORKSPACE}/install" >> "$GITHUB_ENV"

      - name: Download rspamd binary from build job
        uses: actions/download-artifact@v4
        with:
          name: rspamd-binary-ubuntu-ci
          path: ${{ env.PREFIX }}

      - name: Prepare rspamd configuration
        run: |
          mkdir -p ${PREFIX}/etc/rspamd/local.d
          cp -r src/conf/* ${PREFIX}/etc/rspamd/
          echo 'static_dir = "${PREFIX}/share/rspamd/www";' > ${PREFIX}/etc/rspamd/local.d/worker-controller.inc
          echo 'password = "$2$8y16z4benwtsemhhcsdtxc6zem1muuhj$pufmrdhm41s53eccisds6rxych3khq493jhqra8r1i3jto93dt7b";' >> ${PREFIX}/etc/rspamd/local.d/worker-controller.inc
          echo 'enable_password = "$2$hkmgaqejragy47tfe18k7r8zf4wwfegt$jdrfna838b9f4mqu73q858t3zjpse1kw8mw7e6yeftabq1of1sry";' >> ${PREFIX}/etc/rspamd/local.d/worker-controller.inc
          echo 'secure_ip = "0";' >> ${PREFIX}/etc/rspamd/local.d/worker-controller.inc
          cat > ${PREFIX}/etc/rspamd/local.d/logging.inc << 'EOF'
          type = "console";
          level = "error";
          EOF
          # Disable multimap module to prevent hyperscan cache issues at runtime
          echo 'enabled = false;' > ${PREFIX}/etc/rspamd/local.d/multimap.conf
          # Disable redis dependent modules for WebUI tests
          echo 'redis { enabled = false; }' > ${PREFIX}/etc/rspamd/local.d/modules.conf
          chmod +x ${PREFIX}/bin/rspamd
          sudo mkdir -p /var/run/rspamd /var/lib/rspamd
          sudo chown $USER:$USER /var/run/rspamd /var/lib/rspamd

      - name: Install curl
        run: yum install -y curl || apt-get update && apt-get install -y curl

      - name: Start rspamd and wait for WebUI
        shell: bash -e {0}
        run: |
          ${PREFIX}/bin/rspamd -c ${PREFIX}/etc/rspamd/rspamd.conf --insecure &
          # Initial delay before polling (in seconds)
          initial_delay=5
          sleep "$initial_delay"
          # Wait up to 60 seconds for WebUI to respond
          max_retries=30
          for i in $(seq 1 "$max_retries"); do
            http_code=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:11334/ping || true)
            if [[ "$http_code" == "200" ]]; then
              elapsed=$(( initial_delay + (i - 1) * 2 ))
              echo "Rspamd WebUI is up (HTTP 200) after $elapsed seconds"
              break
            elif [[ "$http_code" != "000" ]]; then
              echo "Unexpected HTTP code $http_code from /ping; failing"
              exit 1
            fi
            echo "Waiting for rspamd... ($i/$max_retries)"
            sleep 2
          done

          if [[ "$i" -eq "$max_retries" && "$http_code" != "200" ]]; then
            total_wait=$(( initial_delay + max_retries * 2 ))
            echo "ERROR: rspamd WebUI did not become available after $total_wait seconds"
            exit 1
          fi

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache Playwright browsers (legacy)
        uses: actions/cache@v4
        with:
          path: .cache/ms-playwright-legacy
          key: browsers-legacy-${{ runner.os }}

      - name: Cache Playwright browsers (latest)
        uses: actions/cache@v4
        with:
          path: .cache/ms-playwright-latest
          key: browsers-latest-${{ runner.os }}

      - name: Run Playwright tests (legacy and latest)
        env:
          HOME: /root
        run: |
          set -e
          for version in "1.45.3 legacy" "latest latest"; do
            ver=${version% *}
            label=${version#* }

            echo "=== Running Playwright $ver ($label) ==="

            mkdir -p test-$label
            cp -r src/test/playwright test-$label/
            cd test-$label/playwright

            npm init -y --silent

            echo "::group::Installing Playwright $label"
            npm install --no-save --silent @playwright/test@$ver

            export PLAYWRIGHT_BROWSERS_PATH=$GITHUB_WORKSPACE/.cache/ms-playwright-$label

            npx playwright --version
            npx playwright install --with-deps 2>&1 | tr '\r' '\n' | sed 's/\x1b\[[0-9;]*m//g' | grep Downloading || true

            echo "::endgroup::"

            echo "::group::Running tests ($label)"
            npx playwright test --output=../../playwright-report-$label
            echo "::endgroup::"

            cd ../..
          done

      - name: Upload Playwright reports (legacy)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-legacy
          path: playwright-report-legacy/
          if-no-files-found: ignore

      - name: Upload Playwright reports (latest)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-latest
          path: playwright-report-latest/
          if-no-files-found: ignore
